name: Enna Chocolate
favicon: null
layout_spectrum: 0.99709
typography_spectrum: 0.48835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0e0e0'
    - '#ac9d93'
    - '#0f0607'
    - '#412b2a'
    - '#7c6d63'
  brandStrength: 0.6875
  lightness: 0.6896953424438834
  saturation: 0.6875
  rhythmicContrast: 0.15618296014145017
purpose: []
