name: Enna Chocolate
favicon: null
layout_spectrum: 0.26311
typography_spectrum: 0.48835
title: bean to bar chocolate
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080403'
    - '#291b14'
    - '#4e362a'
    - '#cbcad1'
    - '#a5928f'
  brandStrength: 0.5
  lightness: 0.6896953424438834
  saturation: 0.5
  rhythmicContrast: 0.15618296014145017
purpose: []
